version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: chivesave_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chivesave_db
    ports:
      - "5432:5432"
    volumes:
      - chivesave_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d chivesave_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: chivesave_app
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/chivesave_db
      SECRET_KEY: your-super-secret-jwt-key-change-this-in-production! # IMPORTANT: Change this!
      ACCESS_TOKEN_EXPIRE_MINUTES: 60
    ports:
      - "8000:8000"
    volumes:
      - ./artifacts:/app/artifacts
      - ./current_active_artifact:/app/current_active_artifact
    depends_on:
      db:
        condition: service_healthy
    # Command to run the application, pointing to the new app.main module
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

volumes:
  chivesave_data:
